### ISSUE TITLE
FOR UPDATE SKIP LOCKED

### ISSUE THREAD

**Issue by rozpuh** [michalsn/codeigniter-queue#39]
MariaDb 10.5 not work query 
```sql
SELECT *
FROM `queue_jobs`
WHERE `queue` = 'price_import'
AND `status` = 0
AND `available_at` <= 1707854930
AND `priority` IN ('default')
ORDER BY `available_at` ASC, `id` ASC
 LIMIT 1 FOR UPDATE SKIP LOCKED
```

**Comment by michalsn** [comment]
You need MariaDB 10.6: https://mariadb.com/kb/en/select/#skip-locked

**Comment by adalgdev** [comment]
Same issue for me in MySQL 5.7. Which databases versions are supported?

**Comment by michalsn** [comment]
You need MySQL 8.0.1: https://dev.mysql.com/blog-archive/mysql-8-0-1-using-skip-locked-and-nowait-to-handle-hot-rows/

MySQL 5.7 already reached EOL.

**Comment by kenjis** [comment]
I sent #40
