### ISSUE TITLE
Dev: Postgresql queue:jobs

### ISSUE THREAD

**Issue by kimoudev** [michalsn/codeigniter-queue#45]
Hello everyone,
I don't know if you have performed any operations on postgresql.
I can't consume the jobs
php spark queue:job Email

attached the error image
![Capture d’écran 2024-07-10 à 22 30 10](https://github.com/codeigniter4/queue/assets/6891046/032d3778-b288-45e3-80d1-90584c6253c5)

Thanks,

**Comment by warcooft** [comment]
Same problem, currently I commented out this line of code to make it work with the postgres db driver:

https://github.com/codeigniter4/queue/blob/bcca098b104bd70c25620b5ba5acd2ee870d2556/src/Models/QueueJobModel.php#L56

**Comment by kimoudev** [comment]
Thanks! @warcooft
